const Sequelize=require('sequelize');
const Company=require('../models/Company');
const Category=require('../models/Category');
const ProductStatus=require('../models/ProductStatus');
module.exports={
    id:{
      type:Sequelize.INTEGER,
      primaryKey:true,
      autoIncrement:true 
    },
  idCompany:{
      type:Sequelize.INTEGER,
      allowNull:false,
      references:{
          model:{tableName:'company'},
          key:'id'
          }
  },
  name:{
      type:Sequelize.STRING,
      allowNull:false
  },
  description:{
      type:Sequelize.STRING,
      allowNull:false
  },
  price:{
      type:Sequelize.DOUBLE,
      allowNull:false    
  },
  image:{
      type:Sequelize.STRING,
      allowNull:false
  },
  idStatus:{
      type:Sequelize.INTEGER,
      allowNull:false,
      references:{
          model:{tableName:'productStatus'},
          key:'id'
          }
  },
  idCategory:{
      type:Sequelize.INTEGER,
      allowNull:false,
      references:{
      model:{tableName:'productCategory'},
      key:'id'
      }
  },
  updated:{
      type:Sequelize.DATE,
      allowNull:false,
      defaultValue:Sequelize.NOW
  }
  }