const Sequelize=require('sequelize');
const Company=require('../models/Company');
module.exports={
    id:{
      type:Sequelize.INTEGER,
      primaryKey:true 
    },
  idCompany:{
      type:Sequelize.INTEGER,
      allowNull:false,
      references:{
          model:{tableName:'company'},
          key:'id'
          }
  },
  address:{
      type:Sequelize.STRING,
      allowNull:false
  },
  phone:{
      type:Sequelize.INTEGER,
      allowNull:false
  },
  email:{
      type:Sequelize.STRING,
      allowNull:false    
  },
  openHour:{
      type:Sequelize.INTEGER,
      allowNull:false
  },
  closeHour:{
      type:Sequelize.INTEGER,
      allowNull:false
  }
  }