const Sequelize=require('sequelize');
module.exports={
    id:{
      type:Sequelize.INTEGER,
      primaryKey:true 
    },
  email:{
      type:Sequelize.STRING,
      allowNull:false
  },
  password:{
      type:Sequelize.STRING,
      allowNull:false
  },
  name:{
      type:Sequelize.STRING,
      allowNull:false
  },
  phone:{
      type:Sequelize.INTEGER,
      allowNull:false    
  },
  address:{
      type:Sequelize.STRING,
      allowNull:false
  },
  username:{
      type:Sequelize.STRING,
      allowNull:false
  }
  }