const Category=require('./Category');
const Company=require('./Company');
const CompanyStatus=require('./CompanyStatus');

const Detail=require('./Detail');
const Offer=require('./Offer');
const Order=require('./Order');
const PaymentMethod=require('./PaymentMethod');
const Product=require('./Product');
const ProductOffer=require('./ProductOffer');
const ProductOfferStatus=require('./ProductOfferStatus');
const ProductStatus=require('./ProductStatus');
const StatusTransaction=require('./StatusTransaction');
const Store=require('./Store');
const Transaction=require('./Transaction');
const TypeOffer=require('./typeOffer');
const User=require('./User');
/*
//Category.hasMany(Product,{foreigKey:'idCategory',sourceKey:'id'});
//Product.belongsTo(Category,{foreigKey:'idCategory',targetKey:'id',constraints:false});
//Company.hasMany(Product,{foreigKey:'idCompany',sourceKey:'id'});
//Product.belongsTo(Company,{foreigKey:'idCompany',targetKey:'id'});
Company.hasMany(Order,{foreigKey:'idCompany',sourceKey:'id'});
Order.belongsTo(Company,{foreigKey:'idCompany',targetKey:'id'});
Company.hasMany(Store,{foreigKey:'idCompany',sourceKey:'id'});
Store.belongsTo(Company,{foreigKey:'idCompany',targetKey:'id'});
CompanyStatus.hasMany(Company,{foreigKey:'idStatus',sourceKey:'id'});
Company.belongsTo(CompanyStatus,{foreigKey:'idStatus',targetKey:'id'});
Offer.hasMany(ProductOffer,{foreigKey:'idOffer',sourceKey:'id'});
ProductOffer.belongsTo(Offer,{foreigKey:'idOffer',targetKey:'id'});
Order.hasMany(Detail,{foreigKey:'idOrder',sourceKey:'id'});
Detail.belongsTo(Order,{foreigKey:'idOrder',targetKey:'id'});
PaymentMethod.hasMany(Transaction,{foreigKey:'idpaymentMethod',sourceKey:'id'});
Transaction.belongsTo(PaymentMethod,{foreigKey:'idpaymentMethod',target:'id'});
//Product.hasMany(ProductOffer,{foreigKey:'idProduct',sourceKey:'id'});
//ProductOffer.belongsTo(Product,{foreigKey:'idProduct',targetKey:'id'});
ProductOffer.hasMany(Detail,{foreigKey:'idProductOffer',sourceKey:'id'});
Detail.belongsTo(ProductOffer,{foreigKey:'idProductOffer',targetKey:'id'});
ProductOfferStatus.hasMany(ProductOffer,{foreigKey:'status',sourceKey:'id'});
ProductOffer.belongsTo(ProductOfferStatus,{foreigKey:'status',targetKey:'id'});
//ProductStatus.hasMany(Product,{foreigKey:'idStatus',sourceKey:'id'});
//Product.belongsTo(ProductStatus,{foreigKey:'idStatus',targetKey:'id'});
StatusTransaction.hasMany(Transaction,{foreigKey:'idStatus',sourceKey:'id'});
Transaction.belongsTo(StatusTransaction,{foreigKey:'idStatus',targetKey:'id'});
Transaction.hasMany(Order,{foreigKey:'idTransaction',sourceKey:'id'});
Order.belongsTo(Transaction,{foreigKey:'idTransaction',targetKey:'id'});
TypeOffer.hasMany(Offer,{foreigKey:'idType',sourceKey:'id'});
Offer.belongsTo(TypeOffer,{foreigKey:'idType',targetKey:'id'});
User.hasMany(Order,{foreigKey:'idUser',sourceKey:'id'});
Order.belongsTo(User,{foreigKey:'idUser',targetKey:'id'});
User.hasMany(Company,{foreigKey:'idAdmin',sourceKey:'id'});
Company.belongsTo(User,{foreigKey:'idAdmin',targetKey:'id'});
*/
module.exports={Category,Store,User,Product};
